#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -n "$1" && "$1" != '--'* ]]; then
  URL="$1"
  shift
else
  URL="specs/openapi.yml"
fi

echo "==> Starting mock server with URL ${URL}"

# Run prism mock on the given spec
if [ "$1" == "--daemon" ]; then
  npm exec --package=@stainless-api/prism-cli@5.15.0 -- prism mock "$URL" &> .prism.log &

  # Wait for server to come online (timeout after 30s)
  echo -n "Waiting for server"
  iterations=0 # 300 iterations * 0.1s = 30s timeout
  while ! grep -q "✖  fatal\|Prism is listening" ".prism.log" ; do
    if [ "$iterations" -ge 300 ]; then
      echo
      echo "Error: mock server failed to start within 30 seconds"
      cat .prism.log
      exit 1
    fi
    echo -n "."
    sleep 0.1
    iterations=$((iterations + 1))
  done

  if grep -q "✖  fatal" ".prism.log"; then
    cat .prism.log
    exit 1
  fi

  echo
else
  npm exec --package=@stainless-api/prism-cli@5.15.0 -- prism mock "$URL"
fi
